[package]
name = "mtsunday"
version = "0.1.0"
authors = ["Jbbouille <beanbaptiste.petit@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
log = "0.4.0"
env_logger = "0.6.1"
walkdir = "2.2.7"